
CREATE TABLE IF NOT EXISTS test_data (
     id SERIAL PRIMARY KEY,
     message VARCHAR(255) NOT NULL
);

INSERT INTO test_data (message) VALUES ('Hello from the database!');

-- Creating Users table
CREATE TABLE IF NOT EXISTS readwell_users (
     id bigint generated by default as identity,
     email varchar(255),
    is_admin boolean not null,
    password varchar(255),
    primary key (id)
);

CREATE TABLE IF NOT EXISTS generated_otp (
    id bigint generated by default as identity,
    email varchar(255) NOT NULL,
    otp varchar(6) NOT NULL,
    primary key (id)
);

-- INSERT INTO users (email, password, is_admin) VALUES ('admin@example.com', 'admin', TRUE);
-- Example insert statement (optional)
-- INSERT INTO users (email, password, is_admin) VALUES ('admin@example.com', 'hashed_password', TRUE);
