# Dockerfile.postgres
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB=readwell-db
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin

# Expose the port
EXPOSE 5432

# Add healthcheck
HEALTHCHECK CMD pg_isready -U admin
