name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get the most recent tag
        id: get_tag
        run: |
          TAG=$(git tag --sort=-creatordate | head -n 1)
          if [ -z "$TAG" ]; then
            echo "NO tag on the repo, please create a tag"
            TAG="v0.1"  # Default to v0.1 if no tags exist
          fi
          echo "Latest Tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Increment Tag
        id: increment_tag
        run: |
          TAG=${{ env.TAG }}
          # Extract the version number and increment it
          VERSION_NUMBER=$(echo $TAG | grep -o '[0-9]\+$')
          BASE_VERSION=$(echo $TAG | sed 's/[0-9]\+$//')
          NEW_VERSION_NUMBER=$((VERSION_NUMBER + 1))
          NEW_TAG="${BASE_VERSION}${NEW_VERSION_NUMBER}"

          echo "New Tag: $NEW_TAG"
          echo "TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Debug New Tag
        run: |
          echo "Current New TAG is: ${{ env.TAG }}"

      - name: Build and push backend image
        run: |
          if [ -z "${{ env.TAG }}" ]; then
            echo "TAG is empty. Exiting..."
            exit 1
          fi
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/backend:${{ env.TAG }} ./backend-readwell
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:${{ env.TAG }}

      - name: Build and push frontend image
        run: |
          if [ -z "${{ env.TAG }}" ]; then
            echo "TAG is empty. Exiting..."
            exit 1
          fi
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${{ env.TAG }} ./frontend-readwell
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${{ env.TAG }}

      - name: Tag and push commit
        run: |
          if [ -z "${{ env.TAG }}" ]; then
            echo "TAG is empty. Exiting..."
            exit 1
          fi
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}
